export default {
  en: {
    maplestory: 'MapleStory',
    design: 'Design',
    understand: 'I understand',
    isCashFilter: 'Is Cash',
    genderFilter: 'Gender Filter',
    male: 'Male',
    female: 'Female',
    quickView: 'Quick View',
    removeAll: 'Remove All',
    prototype: 'This project is actively being developed and considered a prototype.',
    alpha: 'Public Alpha',
    unofficialNotice: 'The unofficial MapleStory simulator and designer.',
    properties: 'Properties',
    expression: 'Facial Expression',
    action: 'Pose / Action',
    skin: 'Skin'
  },
  jp: {
    maplestory: 'メイプルストーリー',
    design: 'デザイン',
    understand: 'わかります',
    isCashFilter: 'キャッシュショップの商品のみ',
    genderFilter: '性別',
    male: '男性',
    female: '女性',
    quickView: '早見',
    removeAll: 'すべて削除',
    prototype: 'このプロジェクトは積極的に開発され、試作品とみなされています。',
    alpha: 'アルファバージョン',
    unofficialNotice: '非公式のム メイプルストーリーシミュレータ',
    properties: '特性',
    expression: '表情',
    action: 'ポーズ',
    skin: '肌の色'
  },
  kr: {
    maplestory: '메이플 스토리',
    design: '디자인',
    understand: '이해 했어',
    isCashFilter: '캐시 샵 상품 만',
    gender: '성별',
    male: '남성',
    female: '여자',
    quickView: '퀵뷰',
    removeAll: '모두 제거',
    prototype: '이 프로젝트는 활발히 개발되고 프로토 타입으로 간주됩니다.',
    alpha: '알파 버전',
    unofficialNotice: '비공식 메이플 스토리 시뮬레이터 및 디자이너.',
    properties: '특성',
    expression: '표정',
    action: '자세',
    skin: '피부색'
  }
}